apiVersion: v1
kind: Service
metadata:
  name: practice-node-app
  namespace: practice-app
  labels:
    app: practice-node-app
spec:
  selector:
    app: practice-node-app
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP
